version: "3"

services:
  code-editor:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: "soro-kuraima/coxing-code"
    ports:
      - "5000:5000"
      - "3000:3000"
      - "8000:8000"